@HostAddress = https://localhost:7107

GET {{HostAddress}}/books
Accept: application/json

###
GET {{HostAddress}}/books/bb6e9722-3d4c-4747-afa0-67307080641b
Accept: application/json

###
POST {{HostAddress}}/books
Content-Type: application/json
Accept: application/json

{
  "title": "Ghost of Tsushima",
  "author": "Sucker Punch",
  "price": 14.99
}

###
PUT {{HostAddress}}/books
Content-Type: application/json
Accept: application/json

{
  "id": "dd8a387b-99ca-4d0c-b571-8666b20a8e8f",
  "title": "Ghost of Tsushima",
  "author": "Sucker Punch",
  "price": 13.99
}

###
DELETE {{HostAddress}}/books/dd8a387b-99ca-4d0c-b571-8666b20a8e8f
Accept: application/json

###

# Users Module

POST {{HostAddress}}/users/register
Content-Type: application/json
Accept: application/json

{
  "email": "brad@test.com",
  "password": "Password@123"
}

###
POST {{HostAddress}}/users/login
Content-Type: application/json

{
  "email": "brad@test.com",
  "password": "Password@123"
}


###
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJyYWRAdGVzdC5jb20iLCJpYXQiOjE3MzUyNDEzODIsImV4cCI6MTczNTI0NDk4MiwibmJmIjoxNzM1MjQxMzgyfQ.XEUOyDyOmHx1dhHrSDTgjRTloZqRArHbdopDrCyg7tw

POST {{HostAddress}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookId": "7848beab-1281-4e01-9c1a-fd0c0576f2dc",
  "quantity": 1
}